version: "3"

services:
  web1:
    image: registry.adinusa.id/btacademy/nginx
    container_name: web1
    networks:
      - webnet
    ports:
      - "81:80"

  web2:
    image: registry.adinusa.id/btacademy/httpd
    container_name: web2
    networks:
      - webnet
    ports:
      - "82:80"

  haproxy:
    build: ./haproxy
    networks:
      - webnet
    container_name: haproxy
    ports:
      - "80:80"

networks:
  webnet:
